---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sgproapk/easyslidesdownloader.com/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH